# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PaddingLabelExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # pod 'PaddingLabel', '1'

  pod 'PaddingLabel', :path => '../'

  target 'PaddingLabelExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PaddingLabelExampleUITests' do
    # Pods for testing
  end

end
